"""
Azure OpenAI Responses API Skills - Metrics Dashboard.

Reads actual metrics generated by compare_all.py.
Never fabricates or estimates metrics.
"""

import json
import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

logger = logging.getLogger(__name__)
METRICS_FILE = Path(__file__).resolve().parent / "metrics_data.json"


def load_metrics() -> list[dict]:
    if not METRICS_FILE.exists():
        raise FileNotFoundError(f"Metrics file not found: {METRICS_FILE}")
    return json.loads(METRICS_FILE.read_text(encoding="utf-8"))


def format_value(value: object) -> str:
    return str(value) if value is not None else "N/A"


def display_metrics_table(metrics: list[dict]) -> None:
    print("\n" + "=" * 70)
    print("METRICS DASHBOARD")
    print("=" * 70)
    print()
    print(f"{'Method':<25} {'Input':>10} {'Output':>10} {'Total':>10} {'Latency ms':>12}")
    print("-" * 70)
    for item in metrics:
        latency = item.get("latency")
        if latency is None:
            latency_str = "N/A"
        else:
            latency_str = f"{int(latency)}"
        print(
            f"{item.get('method','N/A'):<25}"
            f" {format_value(item.get('input_tokens')):>10}"
            f" {format_value(item.get('output_tokens')):>10}"
            f" {format_value(item.get('total_tokens')):>10}"
            f" {latency_str:>12}"
        )


def display_summary(metrics: list[dict]) -> None:
    valid = [m for m in metrics if m.get("total_tokens") is not None and m.get("latency") is not None]
    print("\nSUMMARY")
    print("-" * 70)
    if not valid:
        print("No valid metric records available.")
        return

    total_tokens = sum(m["total_tokens"] for m in valid)
    avg_latency = sum(m["latency"] for m in valid) / len(valid)
    print(f"Records: {len(metrics)}")
    print(f"Valid Metrics: {len(valid)}")
    print(f"Total Tokens: {total_tokens}")
    print(f"Average Latency: {avg_latency:.1f} ms")


def setup_logging(name: str) -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")


def main() -> None:
    setup_logging(__name__)
    try:
        metrics = load_metrics()
    except Exception as exc:
        logger.error(exc)
        print("Metrics are unavailable. Run 04_compare/compare_all.py first.")
        return

    display_metrics_table(metrics)
    display_summary(metrics)


if __name__ == "__main__":
    main()
